version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly
    labels:
      - dependencies
      - android
    open-pull-requests-limit: 1
    groups:
      android-dependencies:
        patterns:
          - "*"
